---
- name: Install Monitoring Stack
  hosts: all
  become: true
  vars:
    prometheus_version: "2.49.0"
    alertmanager_version: "0.26.0"
    grafana_version: "10.2.3"
    loki_version: "2.9.0"

  tasks:
    - name: Create monitoring users
      user:
        name: "{{ item }}"
        system: yes
        shell: /bin/false
      loop:
        - prometheus
        - alertmanager
        - loki

    - name: Create monitoring directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus
        - /etc/alertmanager
        - /var/lib/alertmanager
        - /etc/loki
        - /var/lib/loki

    - name: Download and install Prometheus
      unarchive:
        src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-arm64.tar.gz"
        dest: /tmp
        remote_src: yes
      register: prometheus_download

    - name: Copy Prometheus binary
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-arm64/prometheus"
        dest: /usr/local/bin/
        mode: '0755'
        remote_src: yes
      when: prometheus_download.changed

    - name: Copy Prometheus config
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        mode: '0644'

    - name: Copy Prometheus service file
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        mode: '0644'

    - name: Download and install Alertmanager
      unarchive:
        src: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-arm64.tar.gz"
        dest: /tmp
        remote_src: yes
      register: alertmanager_download

    - name: Copy Alertmanager binary
      copy:
        src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-arm64/alertmanager"
        dest: /usr/local/bin/
        mode: '0755'
        remote_src: yes
      when: alertmanager_download.changed

    - name: Copy Alertmanager config
      template:
        src: alertmanager.yml.j2
        dest: /etc/alertmanager/alertmanager.yml
        mode: '0644'

    - name: Copy Alertmanager service file
      template:
        src: alertmanager.service.j2
        dest: /etc/systemd/system/alertmanager.service
        mode: '0644'

    - name: Add Grafana repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Download and install Loki
      unarchive:
        src: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-arm64.zip"
        dest: /tmp
        remote_src: yes
      register: loki_download

    - name: Copy Loki binary
      copy:
        src: /tmp/loki-linux-arm64
        dest: /usr/local/bin/loki
        mode: '0755'
        remote_src: yes
      when: loki_download.changed

    - name: Copy Loki config
      template:
        src: loki.yml.j2
        dest: /etc/loki/config.yml
        mode: '0644'

    - name: Copy Loki service file
      template:
        src: loki.service.j2
        dest: /etc/systemd/system/loki.service
        mode: '0644'

    - name: Start and enable monitoring services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
        daemon_reload: yes
      loop:
        - prometheus
        - alertmanager
        - grafana-server
        - loki 