---
- name: Deploy Website
  hosts: all
  become: true
  vars:
    domain: "{{ domain }}"
    php_version: "{{ php_version | default('8.2') }}"
    nginx_config: "{{ nginx_config | default({}) }}"

  tasks:
    - name: Create web root directory
      file:
        path: "/var/www/{{ domain }}"
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Configure Nginx site
      template:
        src: nginx-site.conf.j2
        dest: "/etc/nginx/sites-available/{{ domain }}"
        mode: '0644'

    - name: Enable Nginx site
      file:
        src: "/etc/nginx/sites-available/{{ domain }}"
        dest: "/etc/nginx/sites-enabled/{{ domain }}"
        state: link

    - name: Configure PHP-FPM pool
      template:
        src: php-fpm-pool.conf.j2
        dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ domain }}.conf"
        mode: '0644'

    - name: Restart services
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - nginx
        - "php{{ php_version }}-fpm" 